### PR TITLE
Create Search_in_sorted_rotated_array.cpp

### PR DESCRIPTION
**Pull request by jatinagrawal36**

### CODE REVIEW

**Review by 3NCRY9T3R — COMMENTED** [review]
Kindly add "/Programs/" before the filename and add the file under Programs folder.

**Review by 3NCRY9T3R — CHANGES_REQUESTED** [review]
Kindly add "/Programs/" before the filename and add the file under Programs folder.

**Comment by jatinagrawal36** [comment]
Updated

**Comment by 3NCRY9T3R** [comment]
Upload the files under Programs folder by adding Programs/ at the start of the name.

**Pull request closed without merging**
