### PR TITLE
Create hello.bf

### PR DESCRIPTION
**Pull request by Valeyard1**

### CODE REVIEW

**Comment by 3NCRY9T3R** [comment]
What is this?

**Comment by Valeyard1** [comment]
Brainfuck: https://en.wikipedia.org/wiki/Brainfuck
A programming language lol

**Comment by Valeyard1** [comment]
Why did you mark as invalid?

**Comment by 3NCRY9T3R** [comment]
> Why did you mark as invalid?

Hello world codes are not accepted.

**Pull request closed without merging**
