### PR TITLE
LexicoGraphic_Rank_of_String.cpp

### PR DESCRIPTION
**Pull request by meprasuk**
This program is useful to find the lexicographical rank of the string in O(N) Time Complexity.

### CODE REVIEW

**Comment by 3NCRY9T3R** [comment]
Add extension to the file.

**Comment by meprasuk** [comment]
Added Extension

**Comment by 3NCRY9T3R** [comment]
Add extension to the file not the PR name.

**Comment by 3NCRY9T3R** [comment]
Delete topological file

**Pull request merged**
